### ISSUE TITLE
Backward incompatible change in patch release

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/nbclient#103]
It seems that we should have tagged a 0.5 instead of 0.4.2. #94 was a (much needed) backward incompatible change.

I suggest we tag a 0.5 right away and remove the 0.4.2 and 0.4.3 uploads as broken.

**Comment by SylvainCorlay** [comment]
cc @davidbrochart @MSeal

**Comment by MSeal** [comment]
Sure, I can do that now. Thanks for raising. For others who have a pinned download issue in future, please update to 0.5.0 -- it's equivalent to 0.4.3.

**Comment by MSeal** [comment]
Ok the those two patch releases are yanked (but not deleted) so they'll still resolve for exact matches (e.g. `nbclient==0.4.2`) but pip will avoid them for any other version specification pattern.

**Comment by MSeal** [comment]
I'll leave this issue open for a bit so it's visible for anyone who comes searching about release changes

**Comment by SylvainCorlay** [comment]
> Ok the those two patch releases are yanked (but not deleted) so they'll still resolve for exact matches (e.g. nbclient==0.4.2) but pip will avoid them for any other version specification pattern.

Excellent! I had not thought of that.
