### ISSUE TITLE
Run vs execute cell?

### ISSUE THREAD

**Issue by choldgraf** [jupyter/nbclient#11]
I was looking through the code and was confused by two methods that (from an api standpoint) seem they should be doing the same thing. One is execute_cell (https://github.com/jupyter/nbclient/blob/386e2994eec7c9db443a2adcb0568c54b27b98f9/nbclient/execute.py#L389), and the other is run_cell (https://github.com/jupyter/nbclient/blob/386e2994eec7c9db443a2adcb0568c54b27b98f9/nbclient/execute.py#L504)

It seems like execute_cell is the preferred user-facing choice since it is documented more so. If so, maybe it makes sense to make run_cell a hidden function? Alternatively, we should document what is the difference

**Comment by MSeal** [comment]
I agree that abstraction separation isn't needed. I got a PR up with the two merged.
