### ISSUE TITLE
Can you pass environmental variables to the kernel?

### ISSUE THREAD

**Issue by chrisjsewell** [jupyter/nbclient#115]
I was thinking of this enabling the running of certain setup code something like:

```python
import os

if "JUPYTER_BOOK" in os.environ:
  %config InlineBackend.figure_format = "retina"
  plt.rcParams["axes.spines.right"] = False
  plt.rcParams["axes.spines.top"] = False
```

(related to https://github.com/executablebooks/meta/discussions/151#discussioncomment-85822)

**Comment by MSeal** [comment]
For nbclient environment variables should be getting passed to the kernel process that gets launched by nature of being a subprocess. However it doesn't guarantee that the kernel preserves said environment variables in it's launch configuration. For the ipython kernel it works just fine:

```
$ TEST=5 papermill --log-output envtest.ipynb envtest.ipynb 
Input Notebook:  envtest.ipynb
Output Notebook: envtest.ipynb
Executing notebook with kernel: python3
Executing Cell 1---------------------------------------
Ending Cell 1------------------------------------------
Executing Cell 2---------------------------------------
'5'
Ending Cell 2------------------------------------------
```

with an example using papermill to execute a notebook with nbclient that print the TEST environment variable.

**Comment by chrisjsewell** [comment]
cool cheers
I'll close this then, as question answered 👍
