### ISSUE TITLE
Issue with typing.AscyncGenerator for python 3.6.0

### ISSUE THREAD

**Issue by esvhd** [jupyter/nbclient#118]
Hi there,

I upgraded to `nbconvert 6.0.7` from from `5.6.1` recently, so as part of that I installed `nbclient 0.5.1`. 

```
python 3.6.0
typing 3.7.4.3
notebook 6.1.4
```

I'm running python 3.6.0 on this machine. After the upgraded I started getting these errors when I tried to start a notebook (500, internal error page):

```
#....
File "h:\anaconda3\lib\site-packages\nbclient\client.py", line447, in NotebookClient
  async def async_setup_kernel(self, **kwargs) -> t.AsyncGenerator:
AttributeError: module 'typing' has no attribute 'AsyncGenerator'
```

If I revert back to `nbconvert 5.6.1` life is back to normal again, notebooks can be opened. 

On another machine with python 3.7, I do not see this issue. This might be specifically related to `python 3.6.0`. 

Unfortunately I couldn't upgrade the machine to 3.7 easily... Any idea how / why this was happening to 3.6.0?

Thanks.

**Comment by davidbrochart** [comment]
Hi @esvhd, thanks for opening an issue. I can reproduce the bug, but unfortunately fixing it in nbclient won't be enough since prompt-toolkit also has the issue, and they require python>=3.6.1 for that reason. Out of curiosity, what version of prompt-toolkit do you have?

**Comment by esvhd** [comment]
Hi @davidbrochart , thanks for taking the time to look at this. I'm using `prompt-toolkit 2.0.4` in this environment.

**Comment by davidbrochart** [comment]
I see, I think they didn't have type checking yet in this version, so I guess that a fix in nbclient would work for you. Unfortunately I couldn't find a nice way to ignore the `AsyncGenerator` return type of `async_setup_kernel` depending on the python version.
#119 just removes the type. On the other hand, I'm not sure having this return type is of great value. So if nobody has an objection, I will go ahead and merge it.

**Comment by esvhd** [comment]
Thanks!

**Comment by davidbrochart** [comment]
cc @MSeal @SylvainCorlay 
We can either merge #119 which removes type checking for the return value of `async_setup_kernel`, or require `python>=3.6.1` instead of currently `python>=3.6`.
Thoughts?

**Comment by rgbkrk** [comment]
I'd prefer we require `python >= 3.6.1`

**Comment by SylvainCorlay** [comment]
> I'd prefer we require `python >= 3.6.1`

Same. 3.6.0 will also have outstanding security issues...

**Comment by davidbrochart** [comment]
Sorry @esvhd, we won't support python 3.6.0 anymore.
