### ISSUE TITLE
CellExecutionError not unpickleable

### ISSUE THREAD

**Issue by agoose77** [jupyter/nbclient#121]
## Issue
Unpickling a `CellExecutionError` exception raises 
```traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() missing 2 required positional
```
## Cause
https://github.com/jupyter/nbclient/blob/cac82a3fe6a6e1c2fff13d0b3a946536610a7405/nbclient/exceptions.py#L61-L65

As a subclass of `BaseException`, the `CellExecutionError` uses the default implementation of `__reduce__` that returns the values passed to `BaseException.__init__` followed by the instance dict of the exception.

E.g. the `__reduce__` result might look like
`(<class 'nbclient.exceptions.CellExecutionError'>, ('yikes',), {'traceback': 'yikes', 'ename': 'big', 'evalue': 'yikes'})`

Because of this, at unpickling time, only one argument is passed to the constructor (`"yikes"` in this example), whilst the attribute dictionary should be set later (after construction). Consequently, unpickling fails for `CellExecutionError` because it expects three positional arguments:

## Workaround:
For those who just want a solution, here's a function that can be used as a `concurrent.futures.Executor` initializer:
```python
def _patch_nbclient_exceptions():
    import nbclient.exceptions as exc

    # Fix https://github.com/jupyter/nbclient/issues/121
    def reduce_CellExecutionError(self):
        return type(self), (self.traceback, self.ename, self.evalue)

    exc.CellExecutionError.__reduce__ = reduce_CellExecutionError
```

## Solutions:
- Implement a custom `__reduce__` function that passes the object attributes as positional arguments only
- Implement default values for the other arguments (hack)
- Pass the attributes to the superclass init in the same order as they're defined in the `__init__` signature.

**Comment by davidbrochart** [comment]
Thanks @agoose77, it looks like you already have reasonable solutions for this issue. Would you like to open a PR?

**Comment by agoose77** [comment]
Of course, I opened this PR to get a sense of which solution might be considered the best. Any thoughts? :)

**Comment by davidbrochart** [comment]
> * Implement a custom `__reduce__` function that passes the object attributes as positional arguments only

It looks like this solution is similar to your workaround, which looks good to me.
