### ISSUE TITLE
AssertionError during Kernel Cleanup when running in parallel

### ISSUE THREAD

**Issue by alex-treebeard** [jupyter/nbclient#126]
Hey there,

I'm using jupyter-client (6.1.7) and am sporadically seeing this error when I run a fairly comprehensive test suite:
https://github.com/treebeardtech/nbmake/runs/1485640374?check_suite_focus=true

I am unable to force a repro and am unclear if it correlates with a platform/python version.

I do however think this is related to me using nbclient downstream of pytest-xdist -- perhaps some sort of cleanup race condition.

The test which triggered it in this case runs 10 notebooks in parallel using Jupyter client.

```
2020-12-02T10:32:45.3425428Z Error in atexit._run_exitfuncs:
2020-12-02T10:32:45.3426007Z Traceback (most recent call last):
2020-12-02T10:32:45.3427304Z   File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/nbclient/client.py", line 351, in _async_cleanup_kernel
2020-12-02T10:32:45.3428274Z     assert self.km is not None
2020-12-02T10:32:45.3429057Z AssertionError
```

I'll add more occurrences as I find them and look for patterns, any thoughts appreciated.

**Comment by MSeal** [comment]
Sorry we missed responding to this (I was offline most of Dec). I do believe it is platform specific, but it might not be? Can you reproduce with a fresh environment and latest package dependencies?

**Comment by alex-treebeard** [comment]
Hey @MSeal, now that I try and recall: I believe this stopped happening after a week or so and I was not able to figure out why. Will reopen if this reemerges
