### ISSUE TITLE
Allow specific errors to be ignored when executing cell

### ISSUE THREAD

**Issue by mwaskom** [jupyter/nbclient#129]
This is a feature request.

We are using Jupyter notebooks for [computational tutorials](https://github.com/NeuromatchAcademy/course-content) and have the somewhat odd need for our notebooks to execute while allowing a specific error class to be raised without halting.

The idea is that we ship notebooks with incomplete exercises that students are to fill out, and the exercise stubs raise a `NotImplementedError` to signal when something needs to be completed. We want to ignore those errors in the context of our CI workflow, where we are executing the notebooks using `nbconvert`.

I recently [solved this problem](https://github.com/NeuromatchAcademy/course-content/pull/542) by subclassing the `nbconvert.ExecutePreprocessor` class and overwriting a couple of relevant methods, which happen to be inherited from `nbclient`.

This was a little bit more complicated that it could have been, because we needed only to change the logic in `NotebookClient._check_raise_for_error`, but because that's a private method, I had to also copy the entire `async_execute_cell` method which calls it.

There are two ways that this could be easier for us:

- There is already a system for allowing errors in general. This could be extended to support our use-case of allowing a specific exception class.
- If the `_check_raise_for_error` method were public, it would simplify the process of writing a custom subclass that does bespoke error handling.

Thanks!

**Comment by davidbrochart** [comment]
Thanks for the detailed context.

> * There is already a system for allowing errors in general. This could be extended to support our use-case of allowing a specific exception class.

Yes, I think this could be useful. We could have a new parameter `cell_allows_error_names`, that would ignore errors when executing cells depending on their name. In your particular case:
```python
cell_allows_error_names = ["NotImplementedError"]
```
Is it what you had in mind?

**Comment by mwaskom** [comment]
Yes I think that would solve our problem. The customization that I had to do was almost [embarassingly trivial](https://github.com/NeuromatchAcademy/course-content/pull/542/files#diff-566629cefca2beefd914eb257640be11c4a59ad1fb3d68289a9c62b3386dd2c9R339) and it seems like it would generalize to your suggestion easily.

**Comment by davidbrochart** [comment]
OK, I'll open a PR soon.
