### ISSUE TITLE
Unable to read variables from previous cells.

### ISSUE THREAD

**Issue by StevenBeasley-LOB** [jupyter/nbclient#132]
When executing a notebook with multiple cells the variables from the first cell are not in the second.

Notebook:

    #Cell 1
    import pandas as pd

    # this will be replaced in processing

    source_feather = '../../test_stuff/some.feather'
    destination_feather = '../../stash/out.feather'

    #Cell 2
    # read the data
    df = pd.read_feather(source_feather)

executing the notebook:

    import nbclient
    import nbformat
    from nbparameterise import (
    extract_parameters, replace_definitions, parameter_values
    )
    import sys
    import asyncio

    with open(self.notebook_path) as f:
        nb = nbformat.read(f, as_version=4)
    # Get a list of Parameter objects
    orig_parameters = extract_parameters(nb)
    prefix = get_time_string_for_prefix()
    destination_feather = Path(self.config['save_folder']).joinpath(f'{prefix}_data_observation_output.feather')
    # Update one or more parameters
    params = parameter_values(orig_parameters,
                                source_feather=str(feather_path.absolute()),
                                destination_feather=str(destination_feather.absolute()))

    # Make a notebook object with these definitions
    new_nb = replace_definitions(nb, params, execute=False)

    # Due to this bug need to do some fixing
    # https://github.com/jupyter/nbconvert/issues/1372#issuecomment-691596163
    # See https://bugs.python.org/issue37373 :(
    if sys.version_info[0] == 3 and sys.version_info[1] >= 8 and sys.platform.startswith('win'):
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

    # Execute the notebook with the new parameters
    client = nbclient.NotebookClient(new_nb, timeout=600, kernel_name='python3')
    try:
        output = client.execute()
    except nbclient.exceptions.CellExecutionError as e:
        print(e) # Error here
    finally:
        nbformat.write(new_nb, 'blasjhsdkjgf')
    print(output)

    ## `An error occurred while executing the following cell:

    # read the data

    ## df = pd.read_feather(source_feather)

    ---

    NameError Traceback (most recent call last)
    <ipython-input-2-fedad124a3cd> in <module>
    1 # read the data
    ----> 2 df = pd.read_feather(source_feather)

    NameError: name 'pd' is not defined
    NameError: name 'pd' is not defined

Python:

    {'commit_hash': 'ebfd01dae', 'commit_source': 'installation', 'default_encoding': 'utf-8', 'ipython_path': 'C:\\someting\\something\\IPython', 'ipython_version': '7.20.0', 'os_name': 'nt', 'platform': 'Windows-10-10.0.19041-SP0', 'sys_executable': 'C:\\someting\\something\\Python\\Python39\\python.exe', 'sys_platform': 'win32', 'sys_version': '3.9.0 (tags/v3.9.0:9cf6752, Oct 5 2020, 15:34:40) [MSC ' 'v.1927 64 bit (AMD64)]'} 

PIP

    pandas==1.2.1 jupyter-client==6.1.11 jupyter-core==4.7.1 nbclient==0.5.1 nbconvert==6.0.7 nbformat==5.1.2

**Comment by StevenBeasley-LOB** [comment]
It should also be noted that having the I am also unable to use the source_feather or destination_feather variables from the second cell either

**Comment by davidbrochart** [comment]
I tried running your program, but there are many missing parts: `self`, `feather_path`, `get_time_string_for_prefix`...
Please try to post a minimum reproducible example.

**Comment by StevenBeasley-LOB** [comment]
> I tried running your program, but there are many missing parts: `self`, `feather_path`, `get_time_string_for_prefix`...
> Please try to post a minimum reproducible example.
Sorry, thought I had stripped out most of the stuff. 

Here is a working example:

    from pathlib import Path
    import nbclient
    import nbformat
    from nbparameterise import (
        extract_parameters, replace_definitions, parameter_values
    )
    import sys
    import asyncio
    nb_path = r'./path_to_my_nb.ipynb'
    with open(nb_path) as f:
        nb = nbformat.read(f, as_version=4)
    # Get a list of Parameter objects
    orig_parameters = extract_parameters(nb)
    prefix = 'some.file.prefix'
    source_feather = Path(r'./').joinpath(f'input.feather')
    destination_feather = Path(r'./').joinpath(f'{prefix}_output.feather')
    # Update one or more parameters
    params = parameter_values(orig_parameters,
                                source_feather=str(source_feather.absolute()),
                                destination_feather=str(destination_feather.absolute()))

    # Make a notebook object with these definitions
    new_nb = replace_definitions(nb, params, execute=False)


    # Due to this bug need to do some fixing
    # https://github.com/jupyter/nbconvert/issues/1372#issuecomment-691596163
    # See https://bugs.python.org/issue37373 :(
    if sys.version_info[0] == 3 and sys.version_info[1] >= 8 and sys.platform.startswith('win'):
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

    # Execute the notebook with the new parameters
    client = nbclient.NotebookClient(new_nb, timeout=600, kernel_name='python3')
    try:
        output = client.execute()
    except nbclient.exceptions.CellExecutionError as e:
        print(e) # Error here
    finally:
        nbformat.write(new_nb, 'output.ipynb')
    print(output)


However, as always happens when reporting issues they go away after they have been reported. I'll put this one down to Windows 10 getting rebooted over the weekend. But the code above now works, sorry for any inconvenience!
