### ISSUE TITLE
Tests fail with the latest ipykernel

### ISSUE THREAD

**Issue by frenzymadness** [jupyter/nbclient#136]
It seems that nbclient in a combination with the latest ipykernel 5.5.0 does not work correctly with `raises-exception` tag and test test_run_all_notebooks[Skip Exceptions with Cell Tags.ipynb-opts8] fails:
```
E           AssertionError: assert [{'name': 'stdout', 'output_type': 'stream', 'text': 'ok\n'}] == []
E             Left contains one more item: {'name': 'stdout', 'output_type': 'stream', 'text': 'ok\n'}
E             Full diff:
E             - []
E             + [{'name': 'stdout', 'output_type': 'stream', 'text': 'ok\n'}]
```
It works well for me with ipykernel 5.4.3 so I've reported it to ipykernel: https://github.com/ipython/ipykernel/issues/598
But the truth is that I'm not able to reproduce the same behavior in jupyter notebook so it might not be an error in ipykernel.

**Comment by chrisjsewell** [comment]
Heya yes I can confirm that this issue with `raises-exception` has also manifested in jupyter-book: https://github.com/executablebooks/jupyter-book/issues/1237

**Comment by MSeal** [comment]
Thanks for reporting and it seems the 5.5.0 update is causing test failures in testbook as well. I'm not able to look into the issue in depth for a few days. If someone has bandwidth before that to diagnose the issue it'd be appreciated.

**Comment by glentakahashi** [comment]
Sorry for the issues! I don't fully understand the "raises-exception" tag, but I do have some leads on what might be the problem. I /think/ it's an issue in nbclient, but feel free to correct me if I'm wrong. I wrote up my findings here:
https://github.com/ipython/ipykernel/issues/598#issuecomment-786081089
and https://github.com/ipython/ipykernel/issues/598#issuecomment-786102429

**Comment by davidbrochart** [comment]
Thanks a lot for your help @glentakahashi, I guess the conclusion is that your bug fix in ipykernel revealed a bug in nbclient. And sorry for taking your time on this!
