### ISSUE TITLE
Prepare next ipykernel

### ISSUE THREAD

**Issue by davidbrochart** [jupyter/nbclient#143]
ipykernel 6.0.0 will break our tests, see https://github.com/ipython/ipykernel/pull/635#issuecomment-818714369.
We will need to update the cell outputs of our test notebooks.

**Comment by MSeal** [comment]
Thanks for digging into that -- it looks like we need to soften output error message matching in our tests? I think the new file path names will be randomized yes?

**Comment by davidbrochart** [comment]
Yes, it will be a random file path. I agree that we need to have these tests more tolerant.

**Comment by davidbrochart** [comment]
Now that https://github.com/ipython/ipykernel/pull/652 is merged, tests should pass with ipykernel master if set the following:
```
export IPYKERNEL_CELL_NAME="<IPY-INPUT>"
```

**Comment by davidbrochart** [comment]
Indeed, tests pass in #146. Let's get #147 in to prepare for ipykernel 6.0.
