### ISSUE TITLE
Drop Python 3.6?

### ISSUE THREAD

**Issue by davidbrochart** [jupyter/nbclient#148]
IPython dropped Python 3.6 from version 7.21.0, ipykernel 6 will require IPython 7.23.1, and we use IPython in our tests.
Should we also drop Python 3.6?

**Comment by kevin-bates** [comment]
Thanks for bringing this up David.  Would this only be in regards to our 7.0 release?

I'm surprised `pip` wouldn't just do the right thing - assuming `ipykernel` is properly decorated relative to required releases and we're not relying on functionality only in `ipykernel` 6.

**Comment by davidbrochart** [comment]
> Would this only be in regards to our 7.0 release?

Do you mean jupyter_client 7.0? No, regardless of jupyter_client.

> I'm surprised `pip` wouldn't just do the right thing - assuming `ipykernel` is properly decorated relative to required releases and we're not relying on functionality only in `ipykernel` 6.

Yes, you're right, `pip` couldn't do the right thing in #146 because I explicitly installed ipykernel master. With a constraint of 5<=ipykernel<7 or so, everything should be fine. Thanks Kevin!

**Comment by kevin-bates** [comment]
> Do you mean jupyter_client 7.0? No, regardless of jupyter_client.

Oh my - I knew this would happen one day and I am so sorry!  You are absolutely right, my comment was related to the jupyter_client.
