### ISSUE TITLE
jupyter-run console script entry point conflicts with jupyter_client entry point with the same name

### ISSUE THREAD

**Issue by cpcloud** [jupyter/nbclient#179]
`nbclient` installs [a `console_script` entry point named `jupyter-run`](https://github.com/jupyter/nbclient/blob/master/setup.py#L53), and it depends on `jupyter_client` which also installs its own [`console_script` entry point named `jupyter-run`](https://github.com/jupyter/jupyter_client/blob/master/setup.py#L65).

Which of these is invoked in an environment where `nbclient` is installed? I'd guess that the `nbclient` entry point gets invoked first, and just clobbers the `jupyter-client` entry point.

This causes problems when using package managers that detect bugs like these, and fail to install such packages.

Would it be possible to rename the `nbclient` entry point to something else that doesn't clobber another entry point?

**Comment by davidbrochart** [comment]
Also see https://github.com/jupyter/nbclient/pull/173#issuecomment-968760082.
`jupyter-execute` was recently added to nbclient, then renamed `jupyter-run` for alignment with ipython's `%run` magic. We didn't know about jupyter_client's `jupyter-run`. Maybe we should just drop `jupyter-run` in nbclient and only keep `jupyter-run`.

**Comment by cpcloud** [comment]
@davidbrochart That seems fine to me, though I admit I have little knowledge of exactly how these commands are invoked by users. I myself use `nbclient` indirectly through `nbsphinx` (which has `nbclient` as a transitive dependency from `nbconvert`).

**Comment by davidbrochart** [comment]
@cpcloud I released `0.5.9` where `jupyter run` was removed.
