### ISSUE TITLE
ImportError: cannot import name 'asynccontextmanager'

### ISSUE THREAD

**Issue by maartenbreddels** [jupyter/nbclient#194]
This breaks our CI https://github.com/vaexio/vaex/runs/4816023036?check_suite_focus=true and probably all Python3.6 environments

#184 dropped Python 3.6 support, but 3.6 still picks this up when installing using pip, I think this needs to be configured in setup.py

**Comment by davidbrochart** [comment]
I think it has to do with the conda package, build 0 for v0.5.10 didn't pin python>=3.7. I published build 1 right after, so it should be picked up, but I could mark build 0 as broken.
Could you restart your workflow?

**Comment by maartenbreddels** [comment]
it still picks it up:
```
2022-01-14T13:48:39.6719424Z   + nbclient                             0.5.10  pyhd8ed1ab_0            conda-forge/noarch         63 KB
```
How can you mark something as broken on Conda-forge?

**Comment by davidbrochart** [comment]
Ah you're right, since you have python=3.6 it will pick build 0. I will mark build 1 as broken then.

**Comment by davidbrochart** [comment]
> How can you mark something as broken on Conda-forge?

https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages
See https://github.com/conda-forge/admin-requests/pull/372

**Comment by maartenbreddels** [comment]
Yeah, working now, Thanks David!
