### ISSUE TITLE
Make task for copying changelogs to readthedocs page

### ISSUE THREAD

**Issue by MSeal** [jupyter/nbclient#20]
Either create an automated task to copy and convert the markdown changelogs to the readthedocs /docs path or just move the changelog to rst and place it there (I dislike writing rst by hand).

**Comment by choldgraf** [comment]
Why not use recommonmark to parse the changelog in markdown? Usually I use `CHANGELOG.md` in the root that just has a link to the changelog page in the documentation.

**Comment by MSeal** [comment]
That sounds like a good path to try here. If no one gets to it first I'll give it a try before the next release
