### ISSUE TITLE
Missing one argument on call to _check_raise_for_error()

### ISSUE THREAD

**Issue by PuckCh** [jupyter/nbclient#200]
In client.py, line 965,  the call:
```
await self._check_raise_for_error(cell, cell_index, exec_reply)
```
is missing one parameter.

The definition of _check_raise_for_error added a new parameter `cell_index: int` in commit c68b7001432f5f02ee15c19f1613c08943afbbd3:
```
...
def _check_raise_for_error(
            self,
            cell: NotebookNode,
            cell_index: int,
            exec_reply: t.Optional[t.Dict]) -> None:
...
```

Link to the invalid call for reference: https://github.com/jupyter/nbclient/blob/35e7fb49a984089d2f23e2a18da1d59271a78f42/nbclient/client.py#L965

Have a nice day.

-- Olivier

**Comment by davidbrochart** [comment]
Hi Olivier, I'm not sure to follow. Why do you think the call to `_check_raise_for_error(cell, cell_index, exec_reply)` is invalid? It has the `cell_index` parameter.

**Comment by PuckCh** [comment]
Hi David,

Thanks for the quick reply.
You're right, it seems ok. So, I need to understand why my usage of nbclient 0.5.11 caused the error:
```
      File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_c>
        await self._check_raise_for_error(cell, cell_index, exec_reply)
    TypeError: _check_raise_for_error() takes 3 positional arguments but 4 were given
```
while 0.5.10 cause no problems.

The problem is coming with our setup of nbgrader.
I will investigate more and come back when I have more details.

**Comment by PuckCh** [comment]
Ok, error is in the version of nbgrader I'm using, nothing to do with nbclient.

Sorry for the trouble.

**Comment by davidbrochart** [comment]
No worries, thanks!
