### ISSUE TITLE
Add nbclient to conda-forge

### ISSUE THREAD

**Issue by willingc** [jupyter/nbclient#23]
@MSeal Seem like this would be helpful for packages that depend on nbclient.

**Comment by davidbrochart** [comment]
I opened a PR: https://github.com/conda-forge/staged-recipes/pull/10864

**Comment by MSeal** [comment]
Yep, definitely needs doing. Thanks @davidbrochart for opening a PR! It looks like the build failure atm is with python 2, which isn't supported for nbclient.

**Comment by davidbrochart** [comment]
There is a `SSL: CERTIFICATE_VERIFY_FAILED` error in conda-forge that seems to be affecting all PRs. I mentioned it in the gitter channel. Let's see if it prevents merging.

**Comment by davidbrochart** [comment]
It has been merged, should be in Anaconda in an hour or so.

**Comment by MSeal** [comment]
Thanks btw @davidbrochart, I got the papermill 2.0 recipe fixed now that nbclient is available!
