### ISSUE TITLE
Widget Output objects save wrong display content

### ISSUE THREAD

**Issue by MSeal** [jupyter/nbclient#24]
See https://github.com/jupyter/nbconvert/issues/923 for root-cause analysis and proposal for solution of the issue for the code base when it was in nbconvert.

**Comment by choldgraf** [comment]
I just want to confirm that this is still an unresolved issue, right? I know we've had some changes in nbclient since this opened up but none of that resolve this yeah?

**Comment by MSeal** [comment]
Yep still not solved, too many projects :) It's in my queue of things to go do but my free time has been severely constrained lately.

**Comment by choldgraf** [comment]
Pssshhh next you're gonna tell me that a global crisis has happened or something 😅😭

**Comment by SylvainCorlay** [comment]
Should we move the mechanism we have in Voilà to handle that to nbclient?

The `VoilaExecutor` inerits from `NotebookClient`, and includes a mock `OutputWidget` which mimicks the behavior of the real front-end output widget.

This was developed by @maartenbreddels and I think he should be credited with the commit should this be included in nbclient.

**Comment by choldgraf** [comment]
I was thinking the same thing actually...I think I'd be +1 on it unless somebody else has a cleaner solution in mind

**Comment by SylvainCorlay** [comment]
I think this solution is actually clean.

**Comment by SylvainCorlay** [comment]
We may want to provide a hook for providers of (other) comm targets than jupyter-widgets implementing things that impact the notebook state to provide similar pure python "front ends" like this output widget.

Will open a PR for this tomorrow.

**Comment by choldgraf** [comment]
That's sounds great, I didn't mean to imply this wasn't a clean solution, it seems good to me. I will defer to you all about the right approach 👍

**Comment by MSeal** [comment]
I'm all for adding this from Voilà. While I didn't get around to implementing the same logic I'll gladly review a PR

**Comment by maartenbreddels** [comment]
I agree, I think nbclient is the right place for this. Happy to port the work + test to nbclient.
Long term I think the way the Output widget works should change.

**Comment by MSeal** [comment]
With the 0.4.0 release this is now solved. Note you still have to "Trust Notebook" in classic UI when loading in a browser after execution like other js generating components.. Thanks @maartenbreddels for tackling the implementation!

**Comment by choldgraf** [comment]
Indeed, thanks so much @maartenbreddels :-)
