### ISSUE TITLE
just_run does not close event loop it creates

### ISSUE THREAD

**Issue by akx** [jupyter/nbclient#249]
If there is no running event loop, `nbclient.util.just_run`, as used by `nbclient.util.run_sync`, as used by the synchronous `NotebookClient.execute()` wrapper, creates a new event loop but never closes it:

https://github.com/jupyter/nbclient/blob/4e99419a6cc727e2436f1e49f865cff2262f0d98/nbclient/util.py#L40-L60

This could cause ResourceWarnings: https://github.com/jupyter/nbconvert/issues/1856

**Comment by davidbrochart** [comment]
Thanks @akx for opening an issue.
I am experimenting with a new implementation in #250.

**Comment by akx** [comment]
Welp, `just_run` is no more, so I guess this was fixed in #259.
