### ISSUE TITLE
jupyter_core version constraint is invalid

### ISSUE THREAD

**Issue by colinjc** [jupyter/nbclient#262]
When v0.7.1 is installed into a Conda environment and we try to export it to a lockfile using `mamba env export` it crashes with the error 

```
>> mamba env export > /lockfile/conda-lockfile.yml
InvalidVersionSpec: Invalid version '!=~5.0': invalid operator
```

This is because `pyproject.toml` has a dependency listed as `jupyter_core>=4.12,!=~5.0`. `!=~`, which is an invalid version specifier.

Valid version specifiers: https://peps.python.org/pep-0440/#version-specifiers

**Comment by davidbrochart** [comment]
Thanks for reporting, I opened #263.

**Comment by colinjc** [comment]
Hey @davidbrochart, just wanted to follow up that the same problem exists in the following three Jupyter related repos. I can make issues in each if you want?

https://github.com/jupyter-server/jupyter_server/blob/ed99ddcf93fb5812b786447c1dd9faa1642e4521/pyproject.toml#L34
https://github.com/jupyter/jupyter_client/blob/9a3fd39fc44d8b8fcb343ce2817666642e04dcd4/pyproject.toml#L28
https://github.com/jupyterlab/maintainer-tools/blob/a8a740268da194f655a9cca5e5aef02fc06c5716/pyproject.toml#L10
