### ISSUE TITLE
Initial 0.1.0 Release Plan

### ISSUE THREAD

**Issue by MSeal** [jupyter/nbclient#3]
- [x] Point readthedocs to this repo
- [x] Setup circileci to look at this repo
- [ ] Automate a changelog copy to docs page?
- [ ] Do the first release (0.1.0?)
- [ ] Update nbconvert 6.0 alpha to import this package
- [ ] Update papermill 2.0 (master) to import this package

**Comment by MSeal** [comment]
https://nbclient.readthedocs.io/en/latest/ for readthedocs now done

**Comment by MSeal** [comment]
https://codecov.io/gh/jupyter/nbclient for codecoverage

**Comment by choldgraf** [comment]
FYI I tried out the library using the instructions from the documentation and it worked great :-)

**Comment by rgbkrk** [comment]
Wahoo!

**Comment by MSeal** [comment]
I'll look at moving or making a auotmated copy for the changelog this week and get the first release rolled out soon with a few of the smaller PRs that have been submitted (whenever I get long enough to sit down and do it). Thanks for taking a look at the changes everyone :)

**Comment by MSeal** [comment]
0.1.0 is released!

I added https://github.com/jupyter/nbclient/issues/20 for future work and https://github.com/nteract/papermill/pull/472 is already up with the dependency change. I'll do the same for nbconvert once I get a chance.

**Comment by choldgraf** [comment]
amazing! many thanks to you @MSeal for pushing through the creation and improvement of this repository!
