### ISSUE TITLE
nbclient.client.setup_kernel context manager does not shutdown kernel on exit

### ISSUE THREAD

**Issue by roman-kouzmenko** [jupyter/nbclient#42]
Discovered while investigating a suspected memory leak in the downstream papermill library.

I had to monkey patch this to insert `self.km.shutdown_kernel()` to make it work.

**Comment by davidbrochart** [comment]
Yes, it should be fixed it in #34.

**Comment by MSeal** [comment]
Change was shipped in 0.2.0 release. Please let us know if you run into it again or notice anything else off.
