### ISSUE TITLE
async_execute always creates a new kernel client

### ISSUE THREAD

**Issue by davidbrochart** [jupyter/nbclient#43]
Should we allow the possibility to pass an external kernel client?

**Comment by maartenbreddels** [comment]
Or get it from the kernel manager?

**Comment by davidbrochart** [comment]
> Or get it from the kernel manager?

So that would work already if we didn't [call reset_execution_trackers](https://github.com/jupyter/nbclient/blob/e91436b1d4672046355621fa912f91c9a45dffbb/nbclient/client.py#L439), or if we didn't [reset the client in it](https://github.com/jupyter/nbclient/blob/e91436b1d4672046355621fa912f91c9a45dffbb/nbclient/client.py#L306).

**Comment by MSeal** [comment]
Perhaps we should have a flag to reset or not reset the kc on execution, so
we can pull it from the km? I'd prefer we do that to passing it in because
users might pass kc's not associated with the km and that would cause
issues in cleanup.

**Comment by davidbrochart** [comment]
I like the idea, PR here: https://github.com/jupyter/nbclient/pull/44
