### ISSUE TITLE
Allow the kernel manager to shut down gracefully in _async_cleanup_kernel

### ISSUE THREAD

**Issue by golf-player** [jupyter/nbclient#60]
Referencing this code here:
https://github.com/jupyter/nbclient/blob/0.3.0/nbclient/client.py#L331-L348

`client.shutdown` only sends the shutdown message to the kernel. When it completes its execution, it's not guaranteed that the kernel is shutdown. And immediately after that, the kernel manager is force-killing the kernel, using SIGKILL. (I haven't experienced this before, but couldn't shutdown hooks be affected by this?) 

Since I don't know much about the decision to implement this function in this way, I'd like your input on potentially changing it to try a graceful shutdown using the kernelmanager with a timeout or something before forcefully terminating.

**Comment by golf-player** [comment]
CC: @kevin-bates

**Comment by kevin-bates** [comment]
Yes, I think the nbclient shutdown sequence should allow the kernel manager to perform a graceful shutdown (now=False).  This allows implementations of `request_shutdown` and `finish_shutdown` to perform actions and `finish_shutdown` will [trigger the equivalent of an immediate shutdown via `_kill_kernel()` anyway](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/manager.py#L335-L338).

With remote kernels, the actions necessary during graceful shutdowns include enlisting the help of associated resource managers (YARN, k8s, etc.) to properly stop the "application" (i.e., kernel process) whereas the immediate shutdown, while still enlisting the resource manager, uses more of a brut force termination tactic (e.g., issues KILL via REST API on YARN).  Both approaches are necessary and both occur via the single shutdown call (when now = False).

**Comment by golf-player** [comment]
I've made https://github.com/jupyter/nbclient/pull/64
