### ISSUE TITLE
0.4.0 alpha

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/nbclient#72]
Would anyone be opposed to a prerelease of 0.4.0?

We would like to test the port of the Output widget support in Voilà, and that would simplify CI.

**Comment by choldgraf** [comment]
I'd also love to try this in jupyter book to see if it fixes our issues with ipywidgets not showing up, so +1 from me

**Comment by MSeal** [comment]
Sure, I'll kick one off in a bit then

**Comment by MSeal** [comment]
0.4.0a0 is released fyi

**Comment by choldgraf** [comment]
@MSeal amazing, I will give it a shot
