### ISSUE TITLE
Master test failure

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/nbclient#73]
Thee tests on master appear to be failing on Windows + Python 3.6 over `OSError: [WinError 6] The handle is invalid`.

I re-started the tests to see if this occurs all the time, because the PR that was merged last was passing.

**Comment by SylvainCorlay** [comment]
Edit: always failing on windows-latest 3.6.

**Comment by davidbrochart** [comment]
It looks a lot like the issue we had in [jupyter_server](https://github.com/jupyter/jupyter_server/pull/191#issuecomment-599634432), basically there was a bug in Python on Windows that has been fixed and back-ported to python >= 3.7 (https://bugs.python.org/issue37380).

**Comment by MSeal** [comment]
Thanks for raising. If someone hasn't dug into fixing this in a couple days I should have time at the end of the week to fix builds. There's a number of doc build failures across projects as well that need tweaks to repair :/

**Comment by willingc** [comment]
nbclient doc builds are passing.

**Comment by SylvainCorlay** [comment]
> has been fixed and back-ported to python >= 3.7 (https://bugs.python.org/issue37380).

Thanks! Do you know if there is an advertized workaround so that we don't have to drop support for windows and Python 3.6.

**Comment by davidbrochart** [comment]
I couldn't find any.

**Comment by SylvainCorlay** [comment]
We should ask for one on the CPython issue.

**Comment by davidbrochart** [comment]
See #77

**Comment by MSeal** [comment]
Looks like it's all resolved now. Thanks @davidbrochart !
