### ISSUE TITLE
Rename start_kernel_manager into create_kernel_manager

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/nbclient#92]
The former makes it look like it is starting a kernel or something like this, which it is just instantiating the kernel manager class.

**Comment by davidbrochart** [comment]
Agreed, and that would make it consistent with the docstring:
https://github.com/jupyter/nbclient/blob/bf77f5ac3f3349c91d4fca40b2b909f254379fb7/nbclient/client.py#L325

**Comment by davidbrochart** [comment]
Fixed in #94
